### ISSUE TITLE
How to use lares in Shiny?

### ISSUE THREAD

**Issue by DeLaRiva** [laresbernardo/lareshiny#1]
Hi,

I would like to use your package (Lares) in a Shiny app. Hence, I'm glad that there seems to be a way to do so but how do I?

Thanks in advance!
Best, Ben

**Comment by laresbernardo** [comment]
Hi Ben! This is actually an independent package I created to post useful Shiny functions I frequently use. The only function that actually interacts with `lares` is the [`model_exporter()`](https://github.com/laresbernardo/lareshiny/blob/master/R/models.R) helper function.
Thanks for your interest though, feel free to create a PR if you develop something and would like to share your work.
Cheers.
